version: '3.8'

services:
  # flask:
  #   build: .
  #   command: python backservice.py run -h 0.0.0.0
  #   volumes:
  #     - .:/app
  #   ports:
  #     - 5000:5000
  #   env_file:
  #     - ./.env
  postgres:
    container_name: ${DB_HOST}
    restart: on-failure:3
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      db_network:
        aliases:
           - "pdb"
    ports:
      - 5432:5432
    labels:
      - "postgres.app.description=PostgreSQL Database"
      - "postgres.app.role=db"