version: '3.8'

services:
  flask:
    container_name: flask-app
    build: .
    command: flask run --host 0.0.0.0 --port 5000
    ports:
      - 5000:5000
    environment:
      - BASE_URL=${BASE_URL}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_TIMEOUT=${DB_TIMEOUT}
    networks:
      - db_network
    depends_on:
      - db
    labels:
      - "flask.app.description=Flask API Service"
      - "flask.app.role=app"
  db:
    restart: on-failure:3
    container_name: flask-app-db
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./postgres-init/init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the init.sql script
    networks:
      db_network: 
    ports:
      - 5432:5432
    labels:
      - "postgres.app.description=PostgreSQL Database"
      - "postgres.app.role=db"

networks:
  db_network:
    driver: bridge
