name: Flask-Postgres application

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main", "development" ]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      
      - name: Build and run Docker Compose
        run: |
            ls
            docker-compose -f compose.yml up -d --build
            docker container ls
            docker images
            # Retrieve the shortened SHA of the latest commit
            IMAGE_TAG=$(git rev-parse --short ${{ github.sha }})
            echo $IMAGE_TAG
