name: Flask-Postgres application

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main", "development" ]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      
      - name: Check Docker Compose Version
        run: |
          docker-compose version
          
      - name: Priont Docker Compose file
        run: |
          pwd
          ls
          cat compose.yml

      - name: View Docker Compose Logs
        run: |
          docker-compose -f compose.yml logs

          
      - name: Build and run Docker Compose
        run: |
          set -x
          docker-compose -f compose.yml up -d --build
          docker container ls
          docker images
          set +x

